<template>
  <AppShell :navs="navs" search-placeholder="搜索任务或申请单…">
    <main v-if="detail" class="supplement-page">
      <section class="supplement-hero"><div class="hero-icon"><ClipboardPenLine :size="23"/></div><div class="hero-copy"><p class="section-kicker">Action Required</p><h1>{{ detail.status==='RESOLVED'?'补充事项已完成':'请补充采购信息' }}</h1><p>材料提交后将自动回流至采购处理流程。</p></div><span class="status-pill" :class="detail.status.toLowerCase()">{{ statusLabel }}</span></section>
      <WorkflowProgress :steps="steps" :active="activeStep" :caption="statusLabel"/>
      <section class="content-card request-card"><div class="section-heading"><span><AlertCircle :size="18"/></span><div><h2>待处理事项</h2><p>请根据以下说明补齐信息</p></div></div><div class="request-message">{{ detail.supplementContent }}</div><dl class="context-grid"><div><dt>业务编号</dt><dd>{{ detail.businessId }}</dd></div><div><dt>补充类型</dt><dd>{{ typeLabel }}</dd></div></dl></section>
      <section class="content-card form-card"><div class="section-heading"><span><FilePenLine :size="18"/></span><div><h2>补充说明</h2><p>支持填写字段修正、角色说明或驳回处理意见</p></div></div><label for="supplement-content">补充内容</label><textarea id="supplement-content" v-model="content" :disabled="detail.status==='RESOLVED'" rows="7" placeholder="请清晰描述补充或修正的内容…"/><div class="form-meta"><span :class="{warn:content.length>1800}">{{ content.length }} / 2000</span><span>请勿填写与本申请无关的敏感信息</span></div><div class="form-footer"><router-link to="/extractions" class="action-btn ghost">稍后处理</router-link><button class="action-btn primary" :disabled="submitting||!content.trim()||content.length>2000||detail.status==='RESOLVED'" @click="submit"><LoaderCircle v-if="submitting" class="spin" :size="16"/><Send v-else :size="16"/>{{ submitting?'正在提交…':'提交补充材料' }}</button></div></section>
    </main>
    <div v-else class="detail-skeleton"><div class="skeleton" style="height:140px"/><div class="skeleton" style="height:260px"/></div>
  </AppShell>
</template>
<script setup lang="ts">
import { computed,onMounted,ref } from 'vue';import { useRoute } from 'vue-router';import { AlertCircle,ClipboardList,ClipboardPenLine,FilePenLine,ListTodo,LoaderCircle,Send } from 'lucide-vue-next';import AppShell from '@/components/AppShell.vue';import WorkflowProgress from '@/components/WorkflowProgress.vue';import { supplementApi,type SupplementDetail } from '@/api/supplement';import { useToastStore } from '@/stores/toast'
const route=useRoute(),toast=useToastStore(),detail=ref<SupplementDetail|null>(null),content=ref(''),submitting=ref(false);const navs=[{key:'tasks',label:'合同对比',icon:ListTodo,to:'/tasks'},{key:'extractions',label:'采购申请单',icon:ClipboardList,to:'/extractions'}];const typeLabels:Record<string,string>={MISSING_FIELD:'缺失字段',ROLE_REVIEW:'合同角色复核',REJECTED:'审批驳回',FAILURE_RECOVERY:'异常恢复'};const typeLabel=computed(()=>typeLabels[detail.value?.supplementType||'']||detail.value?.supplementType);const statusLabel=computed(()=>({PENDING:'待补充',SUBMITTED:'已提交',RESOLVED:'已完成'}[detail.value?.status||'PENDING']));const activeStep=computed(()=>detail.value?.status==='RESOLVED'?3:detail.value?.status==='SUBMITTED'?2:1);const steps=[{label:'发起请求',detail:'系统已识别'},{label:'填写材料',detail:'等待用户'},{label:'提交处理',detail:'回流业务'},{label:'完成闭环',detail:'状态更新'}];async function load(){const res=await supplementApi.get(Number(route.params.id));detail.value=res.data;content.value=res.data.submittedContent||''}async function submit(){if(!detail.value)return;submitting.value=true;try{const res=await supplementApi.submit(detail.value.id,content.value);detail.value=res.data;toast.success('补充材料已提交')}finally{submitting.value=false}}onMounted(load)
</script>
<style scoped>.supplement-page{max-width:980px;margin:0 auto;display:grid;gap:20px}.supplement-hero{display:flex;align-items:center;gap:16px;padding:24px;border:1px solid #cfe0f8;border-radius:24px;background:linear-gradient(135deg,#f8fbff,#eef5ff);box-shadow:var(--shadow-sm)}.hero-icon{width:50px;height:50px;border-radius:17px;display:grid;place-items:center;background:var(--primary);color:white;box-shadow:0 10px 22px rgba(23,105,224,.22)}.hero-copy{flex:1}.hero-copy h1{margin:0;font-size:23px}.hero-copy>p:last-child{margin:5px 0 0;color:var(--muted-foreground)}.status-pill{padding:7px 12px;border-radius:999px;background:#fff0cf;color:#a16207;font-size:11px;font-weight:700}.status-pill.submitted{background:#e7f0ff;color:var(--primary)}.status-pill.resolved{background:#e7f8ef;color:#078654}.request-card,.form-card{padding:22px}.section-heading{display:flex;align-items:center;gap:11px}.section-heading>span{width:38px;height:38px;border-radius:13px;display:grid;place-items:center;background:#e8f1ff;color:var(--primary)}.section-heading h2{margin:0;font-size:14px}.section-heading p{margin:2px 0 0;color:var(--muted-foreground);font-size:11px}.request-message{margin:18px 0;padding:15px 16px;border-radius:15px;background:#fff8e8;border:1px solid #f8e2ad;line-height:1.75}.context-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin:0}.context-grid div{padding:14px;border-radius:15px;background:var(--muted)}.context-grid dt{font-size:11px;color:var(--muted-foreground)}.context-grid dd{margin:4px 0 0;font-weight:650}.form-card>label{display:block;margin-top:20px;font-size:12px;font-weight:650}.form-card textarea{box-sizing:border-box;width:100%;resize:vertical;margin-top:8px;padding:14px 15px;border:1px solid var(--input);border-radius:16px;background:#fafbfd;color:var(--foreground);outline:none;font:inherit;line-height:1.7;transition:all .22s}.form-card textarea:focus{background:white;border-color:#9dc4f5;box-shadow:0 0 0 4px rgba(23,105,224,.08)}.form-meta,.form-footer{display:flex;justify-content:space-between;gap:14px}.form-meta{margin-top:8px;font-size:10px;color:var(--muted-foreground)}.form-meta .warn{color:var(--destructive)}.form-footer{margin-top:18px;padding-top:18px;border-top:1px solid var(--border)}.spin{animation:spin 1s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}.detail-skeleton{max-width:980px;margin:0 auto;display:grid;gap:20px}@media(max-width:640px){.supplement-hero{align-items:flex-start;flex-wrap:wrap}.status-pill{margin-left:66px}.context-grid{grid-template-columns:1fr}.form-footer{flex-direction:column-reverse}.form-footer .action-btn{width:100%}}
</style>
